# Generated by Django 3.1.3 on 2024-02-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20240216_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='tim_e',
            field=models.CharField(default='', max_length=149),
            preserve_default=False,
        ),
    ]
