# Generated by Django 3.1.3 on 2024-02-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_diary_tim_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.CharField(default='', max_length=149),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='age_cat',
            field=models.CharField(default='', max_length=149),
            preserve_default=False,
        ),
    ]
